"""Remove TelegramSubscriber model and table

Revision ID: 1712caa69a78
Revises: 66a22948e237
Create Date: 2025-07-30 12:25:26.208846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1712caa69a78'
down_revision = '66a22948e237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_subscriber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_subscriber',
    sa.Column('chat_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('username', sa.VARCHAR(length=128), nullable=True),
    sa.Column('subscribed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    # ### end Alembic commands ###
