"""Add telegram_chat_id to User model

Revision ID: 4f9803d6999c
Revises: 1712caa69a78
Create Date: 2025-08-13 20:38:43.771004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9803d6999c'
down_revision = '1712caa69a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_telegram_chat_id'), ['telegram_chat_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_telegram_chat_id'), type_='unique')
        batch_op.drop_column('telegram_chat_id')

    # ### end Alembic commands ###
