"""rename storage_path to file_path in file table

Revision ID: 66a22948e237
Revises: 78f3fc91cb16
Create Date: 2025-07-21 19:17:56.246842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a22948e237'
down_revision = '78f3fc91cb16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('storage_path',
               existing_type=sa.VARCHAR(length=512),
               new_column_name='file_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=512),
               new_column_name='storage_path')
    # ### end Alembic commands ###
